package com.gnxrt.ticketgoapi.enums;

public enum EmailType {
    ORDER_CONFIRMATION,
    PAYMENT_FAILED,
    ORDER_CANCELLED,
    ORDER_REFUNDED,
    TICKET,
    TICKET_TRANSFER,
    TICKET_TRANSFER_NOTIFICATION,
    EVENT_REMINDER,
    EVENT_CANCELLED,
    EVENT_APPROVED,
    EVENT_REJECTED,
    VERIFICATION,
    PASSWORD_RESET,
    WELCOME,
    ORGANIZER_REQUEST_RECEIVED,
    ORGANIZER_REQUEST_APPROVED,
    ORGANIZER_REQUEST_REJECTED
}
